name: Build
on:
  push:
    branches:
      - main
  pull_request:

env:
  GO111MODULE: on
  GOPROXY: https://goproxy.cn,direct
  http_proxy: ${{ vars.HTTP_PROXY }}
  https_proxy: ${{ vars.HTTPS_PROXY }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: https://code.haozi.net/actions/checkout@v4
      - uses: https://code.haozi.net/actions/setup-go@v5
        with:
          go-version: 'stable'
          cache: false
      - name: Build
        run: |
          go mod download
          CGO_ENABLED=0 GOAMD64=v3 go build -ldflags '-s -w --extldflags "-static"' -o ${{ vars.PROJECT_NAME }}
      - name: Upload artifact
        uses: https://code.haozi.net/actions/upload-artifact@v3
        with:
          name: ${{ vars.PROJECT_NAME }}
          path: |
            ${{ vars.PROJECT_NAME }}
            database
            public
            storage
  deploy_development:
    runs-on: ubuntu-latest
    needs: build
    environment: development
    steps:
      - name: Download artifact
        uses: https://code.haozi.net/actions/download-artifact@v3
        with:
          name: ${{ vars.PROJECT_NAME }}
          path: .
      - name: Set up SSH
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client sshpass
          mv ${{ vars.PROJECT_NAME }} ${{ vars.PROJECT_NAME }}@new
      - name: Deploy to development
        run: |
          sshpass -p ${{ secrets.DEVELOPMENT_SERVER_PASSWORD }} scp -o StrictHostKeyChecking=no -P ${{ vars.DEVELOPMENT_SERVER_PORT }} -r ${{ vars.PROJECT_NAME }}@new database public storage ${{ vars.DEVELOPMENT_SERVER_USER }}@${{ vars.DEVELOPMENT_SERVER_IP }}:${{ vars.DEVELOPMENT_SERVER_PATH }}
          sshpass -p ${{ secrets.DEVELOPMENT_SERVER_PASSWORD }} ssh -o StrictHostKeyChecking=no -p ${{ vars.DEVELOPMENT_SERVER_PORT }} ${{ vars.DEVELOPMENT_SERVER_USER }}@${{ vars.DEVELOPMENT_SERVER_IP }} "supervisorctl stop ${{ vars.PROJECT_NAME }}" || true
          sshpass -p ${{ secrets.DEVELOPMENT_SERVER_PASSWORD }} ssh -o StrictHostKeyChecking=no -p ${{ vars.DEVELOPMENT_SERVER_PORT }} ${{ vars.DEVELOPMENT_SERVER_USER }}@${{ vars.DEVELOPMENT_SERVER_IP }} "rm -f ${{ vars.DEVELOPMENT_SERVER_PATH }}/${{ vars.PROJECT_NAME }} && mv ${{ vars.DEVELOPMENT_SERVER_PATH }}/${{ vars.PROJECT_NAME }}@new ${{ vars.DEVELOPMENT_SERVER_PATH }}/${{ vars.PROJECT_NAME }} && chmod -R 755 ${{ vars.DEVELOPMENT_SERVER_PATH }} && chown -R www:www ${{ vars.DEVELOPMENT_SERVER_PATH }} && supervisorctl start ${{ vars.PROJECT_NAME }}"
  deploy_production:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    environment: production
    steps:
      - name: Download artifact
        uses: https://code.haozi.net/actions/download-artifact@v3
        with:
          name: ${{ vars.PROJECT_NAME }}
          path: .
      - name: Set up SSH
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client sshpass
          mv ${{ vars.PROJECT_NAME }} ${{ vars.PROJECT_NAME }}@new
      - name: Deploy to production
        run: |
          sshpass -p ${{ secrets.PRODUCTION_SERVER_PASSWORD }} scp -o StrictHostKeyChecking=no -P ${{ vars.PRODUCTION_SERVER_PORT }} -r ${{ vars.PROJECT_NAME }}@new database public storage ${{ vars.PRODUCTION_SERVER_USER }}@${{ vars.PRODUCTION_SERVER_IP }}:${{ vars.PRODUCTION_SERVER_PATH }}
          sshpass -p ${{ secrets.PRODUCTION_SERVER_PASSWORD }} ssh -o StrictHostKeyChecking=no -p ${{ vars.PRODUCTION_SERVER_PORT }} ${{ vars.PRODUCTION_SERVER_USER }}@${{ vars.PRODUCTION_SERVER_IP }} "supervisorctl stop ${{ vars.PROJECT_NAME }}" || true
          sshpass -p ${{ secrets.PRODUCTION_SERVER_PASSWORD }} ssh -o StrictHostKeyChecking=no -p ${{ vars.PRODUCTION_SERVER_PORT }} ${{ vars.PRODUCTION_SERVER_USER }}@${{ vars.PRODUCTION_SERVER_IP }} "rm -f ${{ vars.PRODUCTION_SERVER_PATH }}/${{ vars.PROJECT_NAME }} && mv ${{ vars.PRODUCTION_SERVER_PATH }}/${{ vars.PROJECT_NAME }}@new ${{ vars.PRODUCTION_SERVER_PATH }}/${{ vars.PROJECT_NAME }} && chmod -R 755 ${{ vars.PRODUCTION_SERVER_PATH }} && chown -R www:www ${{ vars.PRODUCTION_SERVER_PATH }} && supervisorctl start ${{ vars.PROJECT_NAME }}"
