name: Build and Deploy
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Build
        run: |
          go mod download
          CGO_ENABLED=0 GOAMD64=v3 go build -ldflags '-s -w --extldflags "-static"' -o ${{ vars.PROJECT_NAME }}
      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ vars.PROJECT_NAME }}
          path: |
            ${{ vars.PROJECT_NAME }}
            database
            public
            storage
  deploy_development:
    runs-on: ubuntu-latest
    needs: build
    environment: development
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ vars.PROJECT_NAME }}
          path: .
      - name: Set up SSH
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client sshpass
      - name: Deploy to development
        env:
          SSHPASS: ${{ secrets.SERVER_PASSWORD }}
        run: |
          mv ${{ vars.PROJECT_NAME }} ${{ vars.PROJECT_NAME }}@new
          sshpass -e scp -o StrictHostKeyChecking=no -P ${{ secrets.SERVER_PORT }} -r ${{ vars.PROJECT_NAME }}@new database public storage ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:${{ secrets.SERVER_PATH }}
          sshpass -e ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "supervisorctl stop ${{ vars.PROJECT_NAME }}" || true
          sshpass -e ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "rm -f ${{ secrets.SERVER_PATH }}/${{ vars.PROJECT_NAME }} && mv ${{ secrets.SERVER_PATH }}/${{ vars.PROJECT_NAME }}@new ${{ secrets.SERVER_PATH }}/${{ vars.PROJECT_NAME }} && chmod -R 755 ${{ secrets.SERVER_PATH }} && chown -R www:www ${{ secrets.SERVER_PATH }} && supervisorctl start ${{ vars.PROJECT_NAME }}"
  deploy_production:
    runs-on: ubuntu-latest
    needs: build
    if: ${{ github.ref == 'refs/heads/main' }}
    environment: production
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: ${{ vars.PROJECT_NAME }}
          path: .
      - name: Set up SSH
        run: |
          sudo apt-get update
          sudo apt-get install -y openssh-client sshpass
      - name: Deploy to production
        env:
          SSHPASS: ${{ secrets.SERVER_PASSWORD }}
        run: |
          mv ${{ vars.PROJECT_NAME }} ${{ vars.PROJECT_NAME }}@new
          sshpass -e scp -o StrictHostKeyChecking=no -P ${{ secrets.SERVER_PORT }} -r ${{ vars.PROJECT_NAME }}@new database public storage ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }}:${{ secrets.SERVER_PATH }}
          sshpass -e ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "supervisorctl stop ${{ vars.PROJECT_NAME }}" || true
          sshpass -e ssh -o StrictHostKeyChecking=no -p ${{ secrets.SERVER_PORT }} ${{ secrets.SERVER_USER }}@${{ secrets.SERVER_IP }} "rm -f ${{ secrets.SERVER_PATH }}/${{ vars.PROJECT_NAME }} && mv ${{ secrets.SERVER_PATH }}/${{ vars.PROJECT_NAME }}@new ${{ secrets.SERVER_PATH }}/${{ vars.PROJECT_NAME }} && chmod -R 755 ${{ secrets.SERVER_PATH }} && chown -R www:www ${{ secrets.SERVER_PATH }} && supervisorctl start ${{ vars.PROJECT_NAME }}"
