name: Lint
on:
  push:
    branches:
      - main
  pull_request:

permissions:
  contents: read

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-go@v5
        with:
          go-version: 'stable'
      - name: Lint
        uses: golangci/golangci-lint-action@v6
        with:
          skip-cache: true
          version: latest
          args: --timeout=30m ./...
